import { type Tool, PDF_ACCEPT, IMAGE_ACCEPT } from './tipos';

/** Ferramentas da categoria "Converter". */
export const CONVERTER: Tool[] = [
  {
    slug: 'imprimir',
    operation: null,
    rota: 'imprimir',
    name: 'Imprimir',
    tagline: 'Fila com fotos, PDFs e Word juntos',
    description:
      'Solte fotos, PDFs, Word, Excel e texto de uma vez. Cada arquivo entra numa fila, é convertido aqui mesmo e sai como um trabalho próprio na impressora, sem precisar juntar tudo num documento antes.',
    icon: 'Printer',
    accent: '52 211 153',
    category: 'Converter',
    accept: [
      'application/pdf',
      '.pdf',
      'image/jpeg',
      'image/png',
      'image/webp',
      '.jpg',
      '.jpeg',
      '.png',
      '.webp',
      '.docx',
      '.xlsx',
      '.pptx',
      '.txt',
    ],
    acceptLabel: 'PDF, imagem, Word, Excel, PowerPoint ou texto',
    multiple: true,
    cta: 'Imprimir',
    fields: [],
  },
  {
    slug: 'pdf-para-jpg',
    operation: 'pdf-to-images',
    name: 'PDF para imagem',
    tagline: 'Cada página vira JPG ou PNG',
    description: 'Renderiza as páginas em alta resolução. Com mais de uma página, entregamos tudo em um .zip.',
    icon: 'ImageIcon',
    accent: '5 150 105',
    category: 'Converter',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Converter para imagem',
    fields: [
      {
        key: 'format',
        type: 'select',
        label: 'Formato',
        default: 'jpeg',
        options: [
          { value: 'jpeg', label: 'JPG', hint: 'leve, ideal para documentos' },
          { value: 'png', label: 'PNG', hint: 'sem perda, arquivos maiores' },
        ],
      },
      { key: 'dpi', type: 'range', label: 'Resolução', default: 150, min: 72, max: 1200, step: 6, unit: 'DPI' },
      {
        key: 'quality',
        type: 'range',
        label: 'Qualidade JPG',
        default: 0.85,
        min: 0.4,
        max: 1,
        step: 0.05,
        showIf: { key: 'format', equals: 'jpeg' },
      },
    ],
  },
  {
    slug: 'jpg-para-pdf',
    operation: 'images-to-pdf',
    name: 'Imagem para PDF',
    tagline: 'Fotos e prints viram um PDF só',
    description: 'Aceita JPG, PNG e WebP. Escolha entre página do tamanho da imagem ou A4 centralizado.',
    icon: 'FileImage',
    accent: '134 239 172',
    category: 'Converter',
    accept: IMAGE_ACCEPT,
    acceptLabel: 'JPG, PNG ou WebP',
    multiple: true,
    orderable: true,
    cta: 'Gerar PDF',
    fields: [
      {
        key: 'formato',
        type: 'select',
        label: 'Tamanho da página',
        default: 'imagem',
        options: [
          { value: 'imagem', label: 'Do tamanho da imagem' },
          { value: 'a4', label: 'A4', hint: '210 × 297 mm' },
          { value: 'a5', label: 'A5', hint: '148 × 210 mm' },
          { value: 'carta', label: 'Carta', hint: '216 × 279 mm' },
          { value: '10x15', label: 'Foto 10 × 15 cm' },
          { value: '13x18', label: 'Foto 13 × 18 cm' },
          { value: 'personalizado', label: 'Personalizado em mm' },
        ],
      },
      {
        key: 'larguraMm',
        type: 'number',
        label: 'Largura',
        default: 50,
        min: 10,
        max: 2000,
        help: 'Em milímetros. Para 50 × 70 cm, use 500 e 700.',
        showIf: { key: 'formato', equals: 'personalizado' },
      },
      {
        key: 'alturaMm',
        type: 'number',
        label: 'Altura',
        default: 70,
        min: 10,
        max: 2000,
        showIf: { key: 'formato', equals: 'personalizado' },
      },
      {
        key: 'ajuste',
        type: 'select',
        label: 'Como encaixar a foto',
        default: 'proporcao',
        options: [
          { value: 'proporcao', label: 'Manter proporção', hint: 'cabe inteira, pode sobrar branco' },
          { value: 'preencher', label: 'Preencher cortando', hint: 'dá um zoom e corta o excesso' },
          { value: 'esticar', label: 'Esticar', hint: 'ocupa tudo, mas distorce' },
        ],
      },
      {
        key: 'orientacao',
        type: 'select',
        label: 'Orientação',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Seguir a foto' },
          { value: 'retrato', label: 'Sempre em pé' },
        ],
      },
      { key: 'margemMm', type: 'range', label: 'Margem', default: 0, min: 0, max: 50, step: 1, unit: 'mm' },
      { key: 'filename', type: 'text', label: 'Nome do arquivo final', default: 'imagens', placeholder: 'imagens' },
    ],
  },
  {
    slug: 'pdf-para-texto',
    operation: 'pdf-to-text',
    name: 'PDF para texto',
    tagline: 'Todo o texto num .txt',
    description:
      'Extrai o texto embutido no PDF, página por página. Em documento digitalizado não há texto para extrair — a gente avisa e sugere rodar a ferramenta de OCR antes.',
    icon: 'FileType',
    accent: '101 163 13',
    category: 'Converter',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Extrair texto',
    fields: [{ key: 'separators', type: 'toggle', label: 'Marcar o número de cada página', default: true }],
  },
  {
    slug: 'ocr-pdf',
    operation: 'ocr',
    name: 'OCR: PDF pesquisável',
    tagline: 'Digitalizou? Isto reconhece o texto',
    description:
      'Roda um motor de OCR inteiro dentro do navegador (baixa alguns megabytes só na primeira vez) e desenha o texto reconhecido, invisível, por cima da imagem original de cada página. A aparência não muda: o que muda é que agora dá para selecionar, copiar e pesquisar o conteúdo.',
    icon: 'ScanText',
    accent: '20 184 166',
    category: 'Converter',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Reconhecer texto',
    fields: [
      {
        key: 'language',
        type: 'select',
        label: 'Idioma do documento',
        default: 'por+eng',
        options: [
          { value: 'por+eng', label: 'Português + Inglês', hint: 'mais lento, cobre os dois' },
          { value: 'por', label: 'Português' },
          { value: 'eng', label: 'Inglês' },
        ],
        help: 'Escolher o idioma certo deixa o reconhecimento mais rápido e mais preciso.',
      },
    ],
  },
  {
    slug: 'word-para-pdf',
    operation: 'word-to-pdf',
    name: 'Word para PDF',
    tagline: 'O texto do .docx vira um PDF',
    description:
      'Lê os parágrafos de um .docx e monta um PDF em A4 com o texto formatado (negrito é preservado). Layout, colunas, imagens e tabelas do original não atravessam.',
    icon: 'FileType2',
    accent: '13 148 136',
    category: 'Converter',
    accept: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document', '.docx'],
    acceptLabel: 'DOCX',
    multiple: true,
    orderable: true,
    cta: 'Converter para PDF',
    fields: [],
  },
  {
    slug: 'pdf-para-word',
    operation: 'pdf-to-word',
    name: 'PDF para Word',
    tagline: 'O texto do PDF num .docx editável',
    description:
      'Extrai o texto embutido no PDF (o mesmo que "PDF para texto" usa) e monta um documento .docx de verdade. Só o texto atravessa: layout, colunas, imagens e tabelas do original não são preservados. Para PDF digitalizado, rode o OCR antes.',
    icon: 'FileType2',
    accent: '13 148 136',
    category: 'Converter',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Converter para Word',
    fields: [],
  },
  {
    slug: 'extrair-imagens',
    operation: 'extract-images',
    name: 'Extrair imagens',
    tagline: 'Tire as fotos de dentro do PDF',
    description:
      'Varre o documento atrás das imagens embutidas e devolve cada uma como arquivo, sem repetir a mesma imagem em páginas diferentes.',
    icon: 'Images',
    accent: '132 204 22',
    category: 'Converter',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Extrair imagens',
    fields: [
      {
        key: 'format',
        type: 'select',
        label: 'Formato',
        default: 'png',
        options: [
          { value: 'png', label: 'PNG', hint: 'sem perda' },
          { value: 'jpeg', label: 'JPG', hint: 'arquivos menores' },
        ],
      },
      {
        key: 'minSize',
        type: 'range',
        label: 'Ignorar imagens menores que',
        default: 64,
        min: 0,
        max: 400,
        step: 8,
        unit: 'px',
        help: 'Evita exportar ícones, linhas e máscaras decorativas.',
      },
    ],
  },
  {
    slug: 'excel-para-pdf',
    operation: 'excel-to-pdf',
    name: 'Excel para PDF',
    tagline: 'As células da planilha viram documento',
    description:
      'Lê as abas de um .xlsx e monta um PDF com as células alinhadas em colunas. Fórmula entra com o resultado que o Excel gravou. Gráficos, imagens, cores e células mescladas não atravessam.',
    icon: 'Table',
    accent: '16 185 129',
    category: 'Converter',
    accept: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '.xlsx'],
    acceptLabel: 'XLSX',
    multiple: true,
    orderable: true,
    cta: 'Converter para PDF',
    fields: [],
  },
  {
    slug: 'powerpoint-para-pdf',
    operation: 'powerpoint-to-pdf',
    name: 'PowerPoint para PDF',
    tagline: 'O texto dos slides num documento',
    description:
      'Lê os slides de um .pptx na ordem e monta um PDF com o texto de cada um. Layout, imagens, cores e animações não atravessam: é o roteiro da apresentação, não a apresentação.',
    icon: 'Presentation',
    accent: '134 239 172',
    category: 'Converter',
    accept: ['application/vnd.openxmlformats-officedocument.presentationml.presentation', '.pptx'],
    acceptLabel: 'PPTX',
    multiple: true,
    orderable: true,
    cta: 'Converter para PDF',
    fields: [],
  },
  {
    slug: 'texto-para-pdf',
    operation: 'text-to-pdf',
    name: 'Texto para PDF',
    tagline: 'Um .txt vira documento',
    description:
      'Lê um arquivo de texto e monta um PDF em A4 com quebra de linha automática. O caminho inverso de "PDF para texto".',
    icon: 'FileText',
    accent: '101 163 13',
    category: 'Converter',
    accept: ['text/plain', '.txt'],
    acceptLabel: 'TXT',
    multiple: true,
    orderable: true,
    cta: 'Gerar PDF',
    fields: [
      { key: 'size', type: 'range', label: 'Tamanho da letra', default: 11, min: 7, max: 18, step: 1, unit: 'pt' },
    ],
  },
];
