import { type Tool, PDF_ACCEPT } from './tipos';

/** Ferramentas da categoria "Editar". */
export const EDITAR: Tool[] = [
  {
    slug: 'girar-pdf',
    operation: 'apply-plan',
    name: 'Girar PDF',
    tagline: 'Clique na página para endireitar',
    description:
      'Cada clique numa miniatura gira aquela página 90°. Se o documento inteiro veio torto, um botão gira todas de uma vez.',
    icon: 'RotateCw',
    accent: '34 197 94',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    board: 'rotate',
    cta: 'Salvar rotação',
    fields: [],
  },
  {
    slug: 'assinar-pdf',
    operation: 'edit',
    name: 'Assinar PDF',
    tagline: 'Desenhe e arraste para onde quiser',
    description:
      'Desenhe a assinatura com o mouse ou o dedo, ou envie uma foto dela. Depois é só arrastar até o lugar certo em qualquer página e ajustar o tamanho pelo canto.',
    icon: 'PenLine',
    accent: '52 211 153',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    editor: 'assinatura',
    cta: 'Salvar assinado',
    fields: [],
  },
  {
    slug: 'editar-pdf',
    operation: 'edit',
    name: 'Editar PDF',
    tagline: 'Escreva, tape e destaque em cima do documento',
    description:
      'Adicione caixas de texto, cubra trechos com um retângulo branco para escrever por cima, passe marca-texto e insira imagens ou assinatura, em qualquer página.',
    icon: 'PencilLine',
    accent: '132 204 22',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    editor: 'completo',
    cta: 'Salvar edições',
    fields: [],
  },
  {
    slug: 'cortar-pdf',
    operation: 'crop',
    name: 'Cortar PDF',
    tagline: 'Corte as margens sobrando',
    description:
      'Reduz a área visível da página por porcentagem em cada lado. Ótimo para tirar margens gigantes de digitalizações.',
    icon: 'Crop',
    accent: '22 163 74',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Cortar',
    fields: [
      { key: 'top', type: 'range', label: 'Topo', default: 0, min: 0, max: 45, step: 1, unit: '%' },
      { key: 'bottom', type: 'range', label: 'Base', default: 0, min: 0, max: 45, step: 1, unit: '%' },
      { key: 'left', type: 'range', label: 'Esquerda', default: 0, min: 0, max: 45, step: 1, unit: '%' },
      { key: 'right', type: 'range', label: 'Direita', default: 0, min: 0, max: 45, step: 1, unit: '%' },
    ],
  },
  {
    slug: 'redimensionar-pdf',
    operation: 'resize',
    name: 'Redimensionar PDF',
    tagline: 'Padronize tudo em A4, Carta ou escala',
    description:
      'Uniformiza páginas de tamanhos diferentes num formato só, centralizando o conteúdo e preservando a orientação de cada uma.',
    icon: 'Scaling',
    accent: '13 148 136',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Redimensionar',
    fields: [
      {
        key: 'target',
        type: 'select',
        label: 'Formato final',
        default: 'a4',
        options: [
          { value: 'a4', label: 'A4', hint: '210 × 297 mm' },
          { value: 'a3', label: 'A3', hint: '297 × 420 mm' },
          { value: 'a5', label: 'A5', hint: '148 × 210 mm' },
          { value: 'carta', label: 'Carta', hint: '216 × 279 mm' },
          { value: 'oficio', label: 'Ofício', hint: '216 × 356 mm' },
          { value: 'personalizado', label: 'Personalizado em mm' },
          { value: 'scale', label: 'Escala livre', hint: 'mantém a proporção original' },
        ],
      },
      {
        key: 'larguraMm',
        type: 'number',
        label: 'Largura',
        default: 210,
        min: 10,
        max: 2000,
        help: 'Em milímetros.',
        showIf: { key: 'target', equals: 'personalizado' },
      },
      {
        key: 'alturaMm',
        type: 'number',
        label: 'Altura',
        default: 297,
        min: 10,
        max: 2000,
        showIf: { key: 'target', equals: 'personalizado' },
      },
      {
        key: 'scale',
        type: 'range',
        label: 'Escala',
        default: 100,
        min: 25,
        max: 400,
        step: 5,
        unit: '%',
        showIf: { key: 'target', equals: 'scale' },
      },
    ],
  },
  {
    slug: 'marca-dagua',
    operation: 'watermark',
    name: 'Marca d’água',
    tagline: 'Assine o documento em todas as páginas',
    description: 'Texto diagonal e translúcido, com opção de repetir em mosaico por toda a página.',
    icon: 'Stamp',
    accent: '110 231 183',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Aplicar marca d’água',
    fields: [
      { key: 'text', type: 'text', label: 'Texto', default: 'CONFIDENCIAL', placeholder: 'CONFIDENCIAL' },
      { key: 'size', type: 'range', label: 'Tamanho', default: 48, min: 10, max: 140, step: 2, unit: 'pt' },
      { key: 'opacity', type: 'range', label: 'Opacidade', default: 0.18, min: 0.03, max: 1, step: 0.03 },
      { key: 'angle', type: 'range', label: 'Inclinação', default: 45, min: -90, max: 90, step: 5, unit: '°' },
      { key: 'shade', type: 'range', label: 'Tom de cinza', default: 0.4, min: 0, max: 1, step: 0.05 },
      { key: 'tile', type: 'toggle', label: 'Repetir em mosaico', default: false },
    ],
  },
  {
    slug: 'numerar-paginas',
    operation: 'page-numbers',
    name: 'Numerar páginas',
    tagline: 'Enumeração no rodapé ou no topo',
    description: 'Adiciona o número de cada página no canto que você escolher, a partir do número inicial que preferir.',
    icon: 'Hash',
    accent: '16 185 129',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Numerar páginas',
    fields: [
      {
        key: 'position',
        type: 'select',
        label: 'Posição',
        default: 'rodape-centro',
        options: [
          { value: 'rodape-centro', label: 'Rodapé, centro' },
          { value: 'rodape-esquerda', label: 'Rodapé, esquerda' },
          { value: 'rodape-direita', label: 'Rodapé, direita' },
          { value: 'topo-centro', label: 'Topo, centro' },
          { value: 'topo-esquerda', label: 'Topo, esquerda' },
          { value: 'topo-direita', label: 'Topo, direita' },
        ],
      },
      {
        key: 'format',
        type: 'select',
        label: 'Formato',
        default: 'numero',
        options: [
          { value: 'numero', label: '1, 2, 3...' },
          { value: 'de-total', label: 'Página 1 de 10' },
        ],
      },
      {
        key: 'startAt',
        type: 'number',
        label: 'Começar a contar em',
        default: 1,
        min: 1,
        max: 9999,
      },
      {
        key: 'size',
        type: 'range',
        label: 'Tamanho',
        default: 11,
        min: 6,
        max: 36,
        step: 1,
        unit: 'pt',
      },
    ],
  },
  {
    slug: 'achatar-pdf',
    operation: 'flatten',
    name: 'Achatar formulário',
    tagline: 'Trave o que já foi preenchido',
    description:
      'Transforma os campos preenchidos em conteúdo fixo da página. O documento continua legível igual, mas ninguém do outro lado consegue mais alterar as respostas.',
    icon: 'Layers',
    accent: '163 230 53',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Achatar campos',
    fields: [],
  },
  {
    slug: 'cabecalho-rodape',
    operation: 'header-footer',
    name: 'Cabeçalho e rodapé',
    tagline: 'Um texto fixo em toda página',
    description:
      'Carimba o mesmo texto no topo e/ou no pé de todas as páginas. Serve para identificação interna, nome do processo ou aviso de confidencialidade.',
    icon: 'Heading',
    accent: '16 185 129',
    category: 'Editar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Carimbar páginas',
    fields: [
      { key: 'header', type: 'text', label: 'Cabeçalho', default: '', placeholder: 'deixe em branco para não usar' },
      { key: 'footer', type: 'text', label: 'Rodapé', default: '', placeholder: 'deixe em branco para não usar' },
      {
        key: 'align',
        type: 'select',
        label: 'Alinhamento',
        default: 'centro',
        options: [
          { value: 'esquerda', label: 'À esquerda' },
          { value: 'centro', label: 'No centro' },
          { value: 'direita', label: 'À direita' },
        ],
      },
      { key: 'size', type: 'range', label: 'Tamanho da letra', default: 10, min: 6, max: 24, step: 1, unit: 'pt' },
    ],
  },
];
