import { IMAGE_ACCEPT, OPCOES_DE_DPI, PDF_ACCEPT, type Field, type Tool } from './tipos';

/**
 * Ferramentas de gráfica: o serviço entre a arte pronta e a máquina.
 *
 * A divisão que importa aqui é outra: montagem de folha e corte rodam em
 * JavaScript e aparecem no site; conferência de cor e chapa precisam ler a
 * página em CMYK, o que só o motor do aplicativo faz, e ficam marcadas com
 * `soNoAplicativo`.
 */

/** Os papéis que as ferramentas de montagem oferecem. */
const PAPEIS: Field = {
  key: 'papel',
  type: 'select',
  label: 'Papel',
  default: 'a4',
  options: [
    { value: 'a4', label: 'A4', hint: '210 x 297 mm' },
    { value: 'a3', label: 'A3', hint: '297 x 420 mm · rende mais por folha' },
    { value: 'carta', label: 'Carta', hint: '215,9 x 279,4 mm' },
    { value: 'oficio', label: 'Ofício', hint: '215,9 x 355,6 mm' },
    { value: 'a5', label: 'A5', hint: '148 x 210 mm' },
  ],
};

const DEITAR: Field = {
  key: 'deitado',
  type: 'toggle',
  label: 'Folha deitada',
  default: false,
  help: 'Vira o papel de lado. Costuma render mais itens quando o que você monta é largo.',
};

export const GRAFICA: Tool[] = [
  {
    slug: 'marcas-de-corte',
    operation: 'crop-marks',
    name: 'Marcas de corte',
    tagline: 'Sangria e marca para a guilhotina',
    description:
      'Põe a arte numa folha maior, com as marcas de corte nos cantos e a sangria em volta. O corte sai na linha certa mesmo quando a guilhotina erra um fio de milímetro, que é o que sempre acontece numa pilha alta.',
    icon: 'Scissors',
    accent: '244 63 94',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Pôr as marcas',
    fields: [
      {
        key: 'sangriaMm',
        type: 'number',
        label: 'Sangria (mm)',
        default: 3,
        min: 0,
        max: 20,
        help: '3 mm é o padrão de gráfica. É a folga que a guilhotina come sem deixar filete branco na borda.',
      },
      {
        key: 'origem',
        type: 'select',
        label: 'A arte já tem sangria?',
        default: 'ja-tem',
        options: [
          { value: 'ja-tem', label: 'Já tem', hint: 'o desenho já passa da linha de corte' },
          { value: 'ampliar', label: 'Não tem — amplie', hint: 'remendo: o desenho cresce um pouco' },
        ],
        help: 'Sangria de verdade vem feita no arquivo original. Ampliar resolve na pressa, mas corta um pouco da beirada.',
      },
      { key: 'marcasMm', type: 'number', label: 'Tamanho da marca (mm)', default: 4, min: 1, max: 15 },
      {
        key: 'registro',
        type: 'toggle',
        label: 'Marcas de registro',
        default: false,
        help: 'O alvo redondo que o impressor usa para alinhar as chapas. Só serve em impressão offset, com mais de uma cor.',
      },
    ],
  },
  {
    slug: 'cartao-de-visita',
    operation: 'business-cards',
    name: 'Cartão de visita',
    tagline: 'Enche a folha e marca onde cortar',
    description:
      'Repete o cartão na folha inteira, centralizado, com as marcas alinhadas nas ruas entre eles. É assim que se corta na guilhotina: a pilha toda de uma vez, e não cartão por cartão.',
    icon: 'CreditCard',
    accent: '139 92 246',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Montar a folha',
    fields: [
      {
        key: 'medida',
        type: 'select',
        label: 'Tamanho do cartão',
        default: '90x50',
        options: [
          { value: '90x50', label: '90 x 50 mm', hint: 'o padrão brasileiro' },
          { value: '88x48', label: '88 x 48 mm', hint: 'cabe mais por folha' },
          { value: '85x55', label: '85 x 55 mm', hint: 'padrão europeu' },
          { value: '89x51', label: '88,9 x 50,8 mm', hint: 'padrão americano (3,5 x 2 pol)' },
          { value: 'personalizado', label: 'Outro', hint: 'você informa a medida' },
        ],
      },
      {
        key: 'larguraMm',
        type: 'number',
        label: 'Largura (mm)',
        default: 90,
        min: 10,
        max: 300,
        showIf: { key: 'medida', equals: 'personalizado' },
      },
      {
        key: 'alturaMm',
        type: 'number',
        label: 'Altura (mm)',
        default: 50,
        min: 10,
        max: 300,
        showIf: { key: 'medida', equals: 'personalizado' },
      },
      { key: 'cartaoDeitado', type: 'toggle', label: 'Cartão deitado', default: true },
      PAPEIS,
      DEITAR,
      {
        key: 'margemMm',
        type: 'number',
        label: 'Margem da folha (mm)',
        default: 5,
        min: 0,
        max: 50,
        help: 'A borda que a impressora não alcança. O que sobrar além disso é dividido igual dos dois lados.',
      },
      {
        key: 'espacoMm',
        type: 'number',
        label: 'Espaço entre cartões (mm)',
        default: 0,
        min: 0,
        max: 30,
        help: 'Zero encosta um no outro e rende mais: um corte só serve aos dois vizinhos.',
      },
      { key: 'marcas', type: 'toggle', label: 'Marcas de corte', default: true },
      {
        key: 'modo',
        type: 'select',
        label: 'Com várias páginas',
        default: 'repetir',
        options: [
          { value: 'repetir', label: 'Uma folha por página', hint: 'frente numa folha, verso na outra' },
          { value: 'sequencia', label: 'Todas na mesma folha', hint: 'cartões diferentes lado a lado' },
        ],
      },
    ],
  },
  {
    slug: 'etiquetas',
    operation: 'labels',
    name: 'Etiquetas e adesivos',
    tagline: 'A grade que couber no papel',
    description:
      'Mesma montagem do cartão, com a medida que você quiser: etiqueta de produto, adesivo, tag, senha de atendimento. Diz quantas couberam antes de você mandar imprimir.',
    icon: 'Tags',
    accent: '234 88 12',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Montar a folha',
    fields: [
      { key: 'larguraMm', type: 'number', label: 'Largura da etiqueta (mm)', default: 50, min: 5, max: 400 },
      { key: 'alturaMm', type: 'number', label: 'Altura da etiqueta (mm)', default: 30, min: 5, max: 400 },
      PAPEIS,
      DEITAR,
      { key: 'margemMm', type: 'number', label: 'Margem da folha (mm)', default: 5, min: 0, max: 50 },
      { key: 'espacoMm', type: 'number', label: 'Espaço entre etiquetas (mm)', default: 2, min: 0, max: 30 },
      { key: 'marcas', type: 'toggle', label: 'Marcas de corte', default: true },
      {
        key: 'modo',
        type: 'select',
        label: 'Com várias páginas',
        default: 'repetir',
        options: [
          { value: 'repetir', label: 'Uma folha por página', hint: 'a mesma etiqueta enchendo a folha' },
          { value: 'sequencia', label: 'Todas na mesma folha', hint: 'etiquetas diferentes lado a lado' },
        ],
      },
    ],
  },
  {
    slug: 'numeracao-sequencial',
    operation: 'sequential-numbering',
    name: 'Numeração sequencial',
    tagline: 'Talão, ingresso, rifa e senha',
    description:
      'Repete o documento com um número diferente em cada cópia. Se o arquivo tem duas páginas — a via e o canhoto —, as duas saem com o mesmo número, que é justamente o que faz o canhoto valer.',
    icon: 'Hash',
    accent: '217 45 32',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Numerar',
    fields: [
      { key: 'quantidade', type: 'number', label: 'Quantos números', default: 100, min: 1, max: 5000 },
      { key: 'inicio', type: 'number', label: 'Começar em', default: 1, min: 0, max: 9999999 },
      {
        key: 'digitos',
        type: 'number',
        label: 'Casas',
        default: 4,
        min: 1,
        max: 10,
        help: 'Completa com zero à esquerda: com 4 casas, o número 7 sai como 0007.',
      },
      { key: 'prefixo', type: 'text', label: 'Prefixo', default: '', placeholder: 'Nº ' },
      {
        key: 'posicao',
        type: 'select',
        label: 'Onde',
        default: 'topo-direita',
        options: [
          { value: 'topo-direita', label: 'Topo, à direita' },
          { value: 'topo-esquerda', label: 'Topo, à esquerda' },
          { value: 'rodape-direita', label: 'Rodapé, à direita' },
          { value: 'rodape-esquerda', label: 'Rodapé, à esquerda' },
        ],
      },
      { key: 'tamanho', type: 'number', label: 'Tamanho da letra', default: 12, min: 5, max: 72 },
      { key: 'margemMm', type: 'number', label: 'Distância da borda (mm)', default: 10, min: 2, max: 60 },
      {
        key: 'cor',
        type: 'text',
        label: 'Cor',
        default: '#d92d20',
        placeholder: '#d92d20',
        help: 'Vermelho por tradição: destaca o número do resto do impresso e dificulta a cópia.',
      },
    ],
  },
  {
    slug: 'espelhar-pdf',
    operation: 'mirror',
    name: 'Espelhar PDF',
    tagline: 'Sublimação, transfer e serigrafia',
    description:
      'Inverte a página como num espelho. É o que a sublimação e o transfer precisam: o desenho é aplicado de cara para baixo, então sai invertido se for impresso do jeito normal.',
    icon: 'FlipHorizontal',
    accent: '20 184 166',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Espelhar',
    fields: [
      {
        key: 'eixo',
        type: 'select',
        label: 'Espelhar',
        default: 'horizontal',
        options: [
          { value: 'horizontal', label: 'Da esquerda para a direita', hint: 'o normal em transfer e sublimação' },
          { value: 'vertical', label: 'De cima para baixo' },
          { value: 'ambos', label: 'Nos dois eixos', hint: 'o mesmo que girar meia-volta' },
        ],
      },
    ],
  },
  {
    slug: 'repetir-paginas',
    operation: 'repeat-pages',
    name: 'Repetir páginas',
    tagline: 'A tiragem toda num arquivo só',
    description:
      'Multiplica as páginas do documento. Serve para mandar a tiragem inteira numa impressão só, já intercalada e pronta para grampear — sem depender de a impressora acertar o número de cópias.',
    icon: 'Copy',
    accent: '99 102 241',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Repetir',
    fields: [
      { key: 'vezes', type: 'number', label: 'Quantas vezes', default: 2, min: 2, max: 500 },
      {
        key: 'modo',
        type: 'select',
        label: 'Como repetir',
        default: 'cada-pagina',
        options: [
          { value: 'cada-pagina', label: 'Cada página seguida', hint: '1, 1, 2, 2, 3, 3' },
          { value: 'documento-inteiro', label: 'O documento inteiro', hint: '1, 2, 3, 1, 2, 3 — já intercalado' },
        ],
      },
    ],
  },
  {
    slug: 'verificar-impressao',
    operation: 'preflight',
    name: 'Conferir antes de imprimir',
    tagline: 'Acha a foto borrada e a fonte que falta',
    description:
      'Mede cada imagem no tamanho em que ela realmente aparece na página e diz quais vão sair serrilhadas; confere se as fontes estão embutidas e se as páginas têm todas a mesma medida. O laudo sai em texto, e diz também o que não foi conferido.',
    icon: 'ScanSearch',
    accent: '2 132 199',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Conferir',
    fields: [],
  },
  {
    slug: 'folha-de-fotos',
    operation: 'photo-sheet',
    name: 'Folha de fotos',
    tagline: '3x4, 5x7, polaroid e adesivo',
    description:
      'Nove 3x4 num 10x15 para documento, e mais onze formatos: passaporte europeu, visto americano, 5x7, polaroid com a tarja de escrever, adesivo redondo e quadrado, e a revelação avulsa em 10x15, 13x18 e 15x20 sem borda branca.',
    icon: 'Images',
    accent: '236 72 153',
    category: 'Gráfica',
    accept: [...IMAGE_ACCEPT, ...PDF_ACCEPT],
    acceptLabel: 'foto ou PDF',
    multiple: false,
    soNoAplicativo: true,
    cta: 'Montar a folha',
    fields: [
      {
        key: 'modelo',
        type: 'select',
        label: 'Formato',
        default: '3x4',
        options: [
          { value: '3x4', label: '3x4 — documento', hint: '30 x 40 mm · o mais pedido no balcão' },
          { value: '3x4-grande', label: '3,5x4,5 — passaporte europeu', hint: '35 x 45 mm' },
          { value: '2x2pol', label: '2x2 pol — visto americano', hint: '51 x 51 mm, quadrada' },
          { value: '5x7', label: '5x7', hint: '50 x 70 mm' },
          { value: '6x9', label: '6x9', hint: '60 x 90 mm' },
          { value: '9x12', label: '9x12', hint: '90 x 120 mm' },
          { value: 'polaroid', label: 'Polaroid', hint: 'com a tarja larga embaixo para escrever' },
          { value: 'adesivo-redondo', label: 'Adesivo redondo 5 cm' },
          { value: 'adesivo-quadrado', label: 'Adesivo quadrado 5 cm' },
          { value: '10x15', label: '10x15 — revelação', hint: 'uma foto só, sem borda' },
          { value: '13x18', label: '13x18 — revelação', hint: 'uma foto só, sem borda' },
          { value: '15x20', label: '15x20 — revelação', hint: 'uma foto só, sem borda' },
        ],
      },
      {
        key: 'papelFoto',
        type: 'select',
        label: 'Papel',
        default: '10x15',
        options: [
          { value: '10x15', label: '10 x 15 cm', hint: 'o papel de foto comum' },
          { value: '13x18', label: '13 x 18 cm' },
          { value: '15x20', label: '15 x 20 cm' },
          { value: '15x21', label: '15 x 21 cm' },
          { value: '20x25', label: '20 x 25 cm' },
          { value: 'A4', label: 'A4', hint: 'rende mais 3x4 por folha' },
          { value: 'A3', label: 'A3' },
        ],
      },
      {
        key: 'quantidade',
        type: 'number',
        label: 'Quantas fotos',
        default: 0,
        min: 0,
        max: 200,
        help: 'Zero enche a folha com quantas couberem.',
      },
      {
        key: 'esticar',
        type: 'toggle',
        label: 'Esticar para preencher',
        default: false,
        help: 'Quando a proporção da foto não bate com a do formato: esticar preenche sem cortar, mas deforma um pouco.',
      },
      {
        key: 'deitar',
        type: 'toggle',
        label: 'Deitar a foto',
        default: false,
        help: 'Vira a foto de lado. Às vezes cabem mais na folha assim.',
      },
      { key: 'margemMm', type: 'number', label: 'Margem (mm)', default: 0, min: 0, max: 30 },
      { key: 'espacoMm', type: 'number', label: 'Espaço entre as fotos (mm)', default: 0, min: 0, max: 30 },
      { key: 'marcas', type: 'toggle', label: 'Marcas de corte', default: true },
      { key: 'dpi', type: 'select', label: 'Resolução', default: '300', options: OPCOES_DE_DPI },
    ],
  },
  {
    slug: 'separar-chapas',
    operation: 'separate-plates',
    name: 'Separar chapas',
    tagline: 'Cada cor sozinha, como vai para a chapa',
    description:
      'Uma página por cor: ciano, magenta, amarelo e preto. É onde se descobre que o preto do texto foi parar nas quatro chapas, ou que um logo que devia ser só ciano tem magenta escondido. Sai em tons de cinza, que é como a chapa é gravada — escuro é onde tem tinta.',
    icon: 'Layers',
    accent: '6 182 212',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    soNoAplicativo: true,
    cta: 'Separar',
    fields: [
      {
        key: 'chapas',
        type: 'select',
        label: 'Quais chapas',
        default: 'cmyk',
        options: [
          { value: 'cmyk', label: 'As quatro', hint: 'ciano, magenta, amarelo e preto' },
          { value: 'k', label: 'Só o preto', hint: 'confere se o texto está mesmo em K puro' },
          { value: 'cmy', label: 'Só as coloridas' },
        ],
      },
      { key: 'dpi', type: 'select', label: 'Resolução', default: '150', options: OPCOES_DE_DPI },
    ],
  },
  {
    slug: 'cobertura-de-tinta',
    operation: 'ink-coverage',
    name: 'Cobertura de tinta',
    tagline: 'Antes de o papel encharcar',
    description:
      'Soma as quatro chapas e diz quanta tinta o papel vai receber. Passar do que ele aguenta faz a tinta repintar na folha de cima, borrar e demorar a secar — e isso só aparece na entrega, não na prova. Sai um laudo em texto, página por página.',
    icon: 'Droplet',
    accent: '124 58 237',
    category: 'Gráfica',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    soNoAplicativo: true,
    cta: 'Medir a tinta',
    fields: [
      {
        key: 'papel',
        type: 'select',
        label: 'Papel',
        default: 'offset',
        options: [
          { value: 'offset', label: 'Offset', hint: 'limite de 300%' },
          { value: 'couche', label: 'Couché', hint: 'limite de 330%' },
          { value: 'jornal', label: 'Jornal', hint: 'limite de 240% · é o que menos aguenta' },
          { value: 'digital', label: 'Digital / toner', hint: 'limite de 400%' },
          { value: 'personalizado', label: 'Outro', hint: 'você informa o limite' },
        ],
      },
      {
        key: 'limite',
        type: 'number',
        label: 'Limite (%)',
        default: 300,
        min: 100,
        max: 400,
        showIf: { key: 'papel', equals: 'personalizado' },
      },
      { key: 'dpi', type: 'select', label: 'Resolução da medição', default: '150', options: OPCOES_DE_DPI },
    ],
  },
];
