import { OPCOES_DE_DPI, type Field, type Tool } from './tipos';

/**
 * Ferramentas de imagem.
 *
 * Todas rodam no navegador, e aparecem no site. Não é escolha de estilo: o
 * motor Python grava só `png, pnm, pgm, ppm, pbm, pam, psd, ps, jpg, jpeg` —
 * não grava webp. O Chromium grava, e ainda decodifica webp e avif sem custar
 * um byte de instalador. É o inverso do que acontece com PDF.
 *
 * Todas aceitam vários arquivos: no balcão nunca é uma foto só.
 */

/** O que o navegador consegue abrir. */
const ENTRADA = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/avif',
  'image/gif',
  'image/bmp',
  '.jpg',
  '.jpeg',
  '.png',
  '.webp',
  '.avif',
  '.gif',
  '.bmp',
];

const FORMATO_DE_SAIDA: Field = {
  key: 'formato',
  type: 'select',
  label: 'Salvar como',
  default: 'jpeg',
  options: [
    { value: 'jpeg', label: 'JPG', hint: 'o mais compatível; não guarda transparência' },
    { value: 'png', label: 'PNG', hint: 'sem perda e com transparência; arquivo maior' },
    { value: 'webp', label: 'WEBP', hint: 'menor que o JPG na mesma qualidade; para web' },
  ],
};

const QUALIDADE: Field = {
  key: 'qualidade',
  type: 'range',
  label: 'Qualidade',
  default: 90,
  min: 30,
  max: 100,
  step: 1,
  unit: '%',
  help: 'Vale para JPG e WEBP. O PNG ignora, porque é sem perda.',
  showIf: { key: 'formato', equals: 'jpeg' },
};

export const IMAGEM: Tool[] = [
  {
    slug: 'converter-imagem',
    operation: 'convert-image',
    name: 'Converter imagem',
    tagline: 'WEBP, PNG, JPG e AVIF, em lote',
    description:
      'Troca o formato de várias imagens de uma vez. Abre WEBP, AVIF, GIF e BMP — que muito programa antigo recusa — e devolve em JPG, PNG ou WEBP. Saindo mais de uma, vem tudo num .zip.',
    icon: 'Repeat',
    accent: '14 165 233',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Converter',
    fields: [FORMATO_DE_SAIDA, QUALIDADE],
  },
  {
    slug: 'redimensionar-imagem',
    operation: 'resize-image',
    name: 'Redimensionar imagem',
    tagline: 'Por medida, por porcentagem ou para impressão',
    description:
      'Muda o tamanho de várias imagens de uma vez. O modo de impressão faz a conta de milímetro para pixel no DPI que você escolher — é o que diz se a foto do cliente aguenta o tamanho pedido.',
    icon: 'Scaling',
    accent: '99 102 241',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Redimensionar',
    fields: [
      {
        key: 'modo',
        type: 'select',
        label: 'Como medir',
        default: 'maior-lado',
        options: [
          { value: 'maior-lado', label: 'Pelo maior lado', hint: 'o outro acompanha a proporção' },
          { value: 'porcento', label: 'Por porcentagem', hint: '50% é metade de cada lado' },
          { value: 'impressao', label: 'Para impressão', hint: 'em milímetros, no DPI escolhido' },
        ],
      },
      {
        key: 'pixels',
        type: 'number',
        label: 'Maior lado (px)',
        default: 1600,
        min: 16,
        max: 20000,
        showIf: { key: 'modo', equals: 'maior-lado' },
      },
      {
        key: 'porcento',
        type: 'range',
        label: 'Tamanho',
        default: 50,
        min: 1,
        max: 400,
        step: 1,
        unit: '%',
        showIf: { key: 'modo', equals: 'porcento' },
      },
      {
        key: 'larguraMm',
        type: 'number',
        label: 'Largura (mm)',
        default: 100,
        min: 1,
        max: 5000,
        showIf: { key: 'modo', equals: 'impressao' },
      },
      {
        key: 'alturaMm',
        type: 'number',
        label: 'Altura (mm)',
        default: 150,
        min: 1,
        max: 5000,
        showIf: { key: 'modo', equals: 'impressao' },
      },
      {
        key: 'dpi',
        type: 'select',
        label: 'Resolução',
        default: '300',
        options: OPCOES_DE_DPI,
        showIf: { key: 'modo', equals: 'impressao' },
      },
      {
        key: 'ajuste',
        type: 'select',
        label: 'Se a proporção não bater',
        default: 'cabe',
        options: [
          { value: 'cabe', label: 'Cabe inteira', hint: 'pode sobrar borda' },
          { value: 'preenche', label: 'Preenche', hint: 'passa da medida e é aparada depois' },
          { value: 'esticar', label: 'Estica', hint: 'medida exata, mas deforma' },
        ],
        showIf: { key: 'modo', equals: 'impressao' },
      },
      {
        key: 'aumentar',
        type: 'toggle',
        label: 'Deixar aumentar',
        default: false,
        help: 'Por padrão a imagem pequena fica como está. Esticar não cria detalhe: entrega o mesmo borrão num arquivo maior.',
      },
      FORMATO_DE_SAIDA,
      QUALIDADE,
    ],
  },
  {
    slug: 'comprimir-imagem',
    operation: 'compress-image',
    name: 'Comprimir imagem',
    tagline: 'Até o peso que o sistema aceitar',
    description:
      'Você diz o peso — "500 KB", "2 MB" — e a ferramenta procura a melhor qualidade que cabe nele. Serve para aquele site do governo que só aceita foto até um tamanho, e para anexo de e-mail.',
    icon: 'Minimize2',
    accent: '16 185 129',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Comprimir',
    fields: [
      {
        key: 'alvo',
        type: 'text',
        label: 'Peso máximo',
        default: '500 KB',
        placeholder: '500 KB',
        help: 'Aceita "500 KB", "1,5 MB" ou o número em bytes.',
      },
      {
        key: 'formato',
        type: 'select',
        label: 'Salvar como',
        default: 'jpeg',
        options: [
          { value: 'jpeg', label: 'JPG', hint: 'o mais compatível' },
          { value: 'webp', label: 'WEBP', hint: 'chega no mesmo peso com mais qualidade' },
        ],
        help: 'O PNG não entra: sendo sem perda, ele não tem como mirar um peso.',
      },
    ],
  },
  {
    slug: 'heic-para-jpg',
    operation: 'heic-to-image',
    name: 'HEIC para JPG',
    tagline: 'A foto que vem do iPhone',
    description:
      'O iPhone grava em HEIC desde 2017, e quase nada abre esse formato — nem o navegador, nem a maioria dos programas de impressão. Aqui a foto vira JPG ou PNG no tamanho original, em lote.',
    icon: 'Smartphone',
    accent: '236 72 153',
    category: 'Imagem',
    accept: ['image/heic', 'image/heif', '.heic', '.heif'],
    acceptLabel: 'HEIC do iPhone',
    multiple: true,
    cta: 'Converter',
    fields: [
      {
        key: 'formato',
        type: 'select',
        label: 'Salvar como',
        default: 'jpeg',
        options: [
          { value: 'jpeg', label: 'JPG', hint: 'o que todo mundo abre' },
          { value: 'png', label: 'PNG', hint: 'sem perda; arquivo bem maior' },
        ],
      },
      {
        key: 'qualidade',
        type: 'range',
        label: 'Qualidade',
        default: 92,
        min: 30,
        max: 100,
        step: 1,
        unit: '%',
        showIf: { key: 'formato', equals: 'jpeg' },
      },
    ],
  },

  // As duas abaixo mexem nos pixels com o motor Lanczos, e não só no
  // formato do arquivo.
  {
    slug: 'melhorar-imagem',
    operation: 'enhance-image',
    name: 'Ampliar e melhorar',
    tagline: 'Lanczos, e não o esticador do Paint',
    description:
      'Aumenta a imagem com reamostragem Lanczos e realça a borda. É o mesmo algoritmo que o Photoshop chama de "bicúbica mais nítida" — bem melhor que o esticador comum, que só borra. Não inventa detalhe que não está no arquivo, e a nota no fim diz isso com todas as letras.',
    icon: 'Sparkles',
    accent: '168 85 247',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Ampliar',
    fields: [
      {
        key: 'escala',
        type: 'select',
        label: 'Quantas vezes maior',
        default: '2',
        options: [
          { value: '1', label: 'Só realçar', hint: 'mantém o tamanho e melhora a borda' },
          { value: '2', label: '2x' },
          { value: '3', label: '3x' },
          { value: '4', label: '4x', hint: 'demora, e o ganho já é pequeno' },
        ],
      },
      {
        key: 'nitidez',
        type: 'range',
        label: 'Realce da borda',
        default: 60,
        min: 0,
        max: 200,
        step: 5,
        unit: '%',
        help: 'Passar de 100% começa a marcar um contorno claro em volta das bordas.',
      },
      {
        key: 'formato',
        type: 'select',
        label: 'Salvar como',
        default: 'png',
        options: [
          { value: 'png', label: 'PNG', hint: 'sem perda; não joga fora o que a ampliação ganhou' },
          { value: 'jpeg', label: 'JPG', hint: 'menor, mas recomprime' },
          { value: 'webp', label: 'WEBP' },
        ],
      },
    ],
  },
  {
    slug: 'cortar-imagem',
    operation: 'crop-image',
    name: 'Cortar imagem',
    tagline: 'Sem a perda que o Paint cobra',
    description:
      'Apara a imagem por margem ou por proporção. O corte em si é cópia de pixel e não perde nada — a perda que aparece no Paint vem de gravar em JPEG de novo, que recomprime a imagem inteira. Por isso o padrão aqui sai em PNG.',
    icon: 'Crop',
    accent: '234 88 12',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Cortar',
    fields: [
      {
        key: 'modo',
        type: 'select',
        label: 'Como cortar',
        default: 'margens',
        options: [
          { value: 'margens', label: 'Tirar das bordas', hint: 'você diz quanto sai de cada lado' },
          { value: 'proporcao', label: 'Numa proporção', hint: 'apara pelo centro até bater a medida' },
        ],
      },
      {
        key: 'proporcao',
        type: 'select',
        label: 'Proporção',
        default: '3x4',
        options: [
          { value: '3x4', label: '3:4 — documento em pé' },
          { value: '4x3', label: '4:3 — foto deitada' },
          { value: '1x1', label: '1:1 — quadrada' },
          { value: '2x3', label: '2:3 — 10x15 em pé' },
          { value: '3x2', label: '3:2 — 10x15 deitada' },
          { value: '16x9', label: '16:9 — tela' },
        ],
        showIf: { key: 'modo', equals: 'proporcao' },
      },
      { key: 'topo', type: 'number', label: 'Tirar do topo (%)', default: 0, min: 0, max: 45, showIf: { key: 'modo', equals: 'margens' } },
      { key: 'base', type: 'number', label: 'Tirar da base (%)', default: 0, min: 0, max: 45, showIf: { key: 'modo', equals: 'margens' } },
      { key: 'esquerda', type: 'number', label: 'Tirar da esquerda (%)', default: 0, min: 0, max: 45, showIf: { key: 'modo', equals: 'margens' } },
      { key: 'direita', type: 'number', label: 'Tirar da direita (%)', default: 0, min: 0, max: 45, showIf: { key: 'modo', equals: 'margens' } },
      {
        key: 'formato',
        type: 'select',
        label: 'Salvar como',
        default: 'png',
        options: [
          { value: 'png', label: 'PNG', hint: 'sem perda: o recorte sai idêntico ao original' },
          { value: 'jpeg', label: 'JPG', hint: 'menor, mas recomprime tudo de novo' },
          { value: 'webp', label: 'WEBP' },
        ],
      },
    ],
  },

  // Daqui para baixo o assunto é o que está desenhado na imagem, e não o
  // formato nem a medida do arquivo.
  {
    slug: 'ajustar-imagem',
    operation: 'adjust-image',
    name: 'Ajustar imagem',
    tagline: 'Brilho, contraste, cor e meio-tom, em lote',
    description:
      'Foto escura, foto lavada, foto que precisa sair em preto e branco. Os quatro ajustes rodam numa passada só — aplicar um por vez, cada um arredondando no fim, é o que abre aquelas faixas visíveis no céu de uma foto. O preto e branco escolhe o corte pela própria imagem, então funciona em digitalização de papel amarelado.',
    icon: 'SlidersHorizontal',
    accent: '245 158 11',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Ajustar',
    fields: [
      { key: 'brilho', type: 'range', label: 'Brilho', default: 0, min: -100, max: 100, step: 1 },
      { key: 'contraste', type: 'range', label: 'Contraste', default: 0, min: -100, max: 100, step: 1 },
      { key: 'saturacao', type: 'range', label: 'Saturação', default: 0, min: -100, max: 100, step: 1 },
      {
        key: 'gama',
        type: 'range',
        label: 'Meio-tom',
        default: 1,
        min: 0.2,
        max: 3,
        step: 0.05,
        help: 'Acima de 1 clareia o meio-tom sem estourar o branco. É o ajuste certo para foto contra a luz.',
      },
      {
        key: 'cor',
        type: 'select',
        label: 'Depois disso',
        default: 'nenhum',
        options: [
          { value: 'nenhum', label: 'Deixar colorida' },
          { value: 'cinza', label: 'Tons de cinza', hint: 'com os pesos que o olho usa, e não a média dos canais' },
          { value: 'sepia', label: 'Sépia', hint: 'o virado de tom da foto antiga' },
          { value: 'pb', label: 'Preto e branco puro', hint: 'só duas cores; para fotocópia e carimbo' },
        ],
      },
      FORMATO_DE_SAIDA,
      QUALIDADE,
    ],
  },
  {
    slug: 'girar-imagem',
    operation: 'rotate-image',
    name: 'Girar e espelhar',
    tagline: 'Sem reamostrar um pixel sequer',
    description:
      'Endireita a foto deitada e espelha quando precisa. Em quarto de volta cada pixel cai exatamente em cima de outro: o resultado é idêntico ao original, sem a perda que um editor cobra ao regravar. Tem a opção de mexer só nas que estão deitadas, para endireitar um lote misto do celular de uma vez.',
    icon: 'RotateCw',
    accent: '6 182 212',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Girar',
    fields: [
      {
        key: 'graus',
        type: 'select',
        label: 'Girar',
        default: '90',
        options: [
          { value: '0', label: 'Não girar' },
          { value: '90', label: '90° para a direita' },
          { value: '180', label: '180°' },
          { value: '270', label: '90° para a esquerda' },
        ],
      },
      {
        key: 'espelho',
        type: 'select',
        label: 'Espelhar',
        default: 'nao',
        options: [
          { value: 'nao', label: 'Não espelhar' },
          { value: 'horizontal', label: 'Na horizontal', hint: 'esquerda vira direita' },
          { value: 'vertical', label: 'Na vertical', hint: 'de cabeça para baixo' },
        ],
      },
      {
        key: 'soDeitadas',
        type: 'toggle',
        label: 'Só as que estão deitadas',
        default: false,
        help: 'As que já estão em pé passam intactas. Serve para endireitar um lote misto de uma vez.',
      },
      {
        key: 'formato',
        type: 'select',
        label: 'Salvar como',
        default: 'png',
        options: [
          { value: 'png', label: 'PNG', hint: 'sem perda: o giro sai idêntico' },
          { value: 'jpeg', label: 'JPG', hint: 'menor, mas recomprime' },
          { value: 'webp', label: 'WEBP' },
        ],
      },
      QUALIDADE,
    ],
  },
  {
    slug: 'remover-fundo',
    operation: 'remove-background',
    name: 'Remover fundo',
    tagline: 'Logo e assinatura vazadas, em PNG',
    description:
      'Apaga o fundo que encosta na borda e devolve PNG com transparência. Não é o mesmo que "apagar tudo que for branco": o miolo de uma letra "O" e o branco de dentro da logo continuam lá. Feito para logo, assinatura digitalizada, carimbo e desenho sobre fundo liso — não para cabelo.',
    icon: 'Eraser',
    accent: '139 92 246',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Remover fundo',
    fields: [
      {
        key: 'tolerancia',
        type: 'range',
        label: 'Tolerância',
        default: 32,
        min: 0,
        max: 120,
        step: 1,
        help: 'Quanto o pixel pode diferir do fundo e ainda sair junto. Fundo com sombra pede mais; desenho de cor clara pede menos.',
      },
      {
        key: 'suavizar',
        type: 'toggle',
        label: 'Suavizar a borda',
        default: true,
        help: 'Tira a escadinha do contorno, que salta aos olhos quando a imagem vai sobre fundo colorido.',
      },
      {
        key: 'trocar',
        type: 'toggle',
        label: 'Pôr uma cor no lugar',
        default: false,
        help: 'Para foto 3x4 com fundo branco, ou catálogo com fundo padrão.',
      },
      {
        key: 'corNova',
        type: 'text',
        label: 'Cor do novo fundo',
        default: '#ffffff',
        placeholder: '#ffffff',
        showIf: { key: 'trocar', equals: true },
      },
      {
        key: 'formato',
        type: 'select',
        label: 'Salvar como',
        default: 'png',
        options: [
          { value: 'png', label: 'PNG' },
          { value: 'jpeg', label: 'JPG' },
          { value: 'webp', label: 'WEBP' },
        ],
        showIf: { key: 'trocar', equals: true },
      },
    ],
  },
  {
    slug: 'limpar-digitalizacao',
    operation: 'clean-scan',
    name: 'Limpar digitalização',
    tagline: 'Papel branco de verdade, e economia de toner',
    description:
      'O que sai do scanner quase nunca tem papel branco: tem cinza, puxado para o amarelo se a folha for velha. Aqui o papel vai para o branco e a tinta para o preto, cada canal de cor com o seu próprio ponto — é o que tira o amarelado em vez de deixá-lo só mais claro. Fundo branco de verdade também deixa de gastar toner.',
    icon: 'ScanLine',
    accent: '2 132 199',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'digitalizações',
    multiple: true,
    cta: 'Limpar',
    fields: [
      {
        key: 'forca',
        type: 'range',
        label: 'Força',
        default: 85,
        min: 0,
        max: 100,
        step: 5,
        unit: '%',
        help: 'No máximo, o papel fica branco puro. Baixe se a digitalização tiver foto, para não estourar o claro dela.',
      },
      {
        key: 'paraPB',
        type: 'toggle',
        label: 'Levar a preto e branco puro',
        default: false,
        help: 'Só duas cores, com o corte escolhido pela própria imagem. É o melhor para fotocópia de documento com texto.',
      },
      FORMATO_DE_SAIDA,
      QUALIDADE,
    ],
  },
  {
    slug: 'moldura-imagem',
    operation: 'border-image',
    name: 'Moldura na imagem',
    tagline: 'Borda e filete, sem reduzir a foto',
    description:
      'Põe uma borda em volta da foto — a margem branca do retrato emoldurado, ou a faixa de cor do catálogo. A imagem não é reduzida para abrir espaço: a moldura vai por fora, e a resolução original continua toda lá para a impressão.',
    icon: 'Frame',
    accent: '190 24 93',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Emoldurar',
    fields: [
      {
        key: 'modo',
        type: 'select',
        label: 'Medir a moldura',
        default: 'porcento',
        options: [
          { value: 'porcento', label: 'Em porcentagem', hint: 'proporcional a cada imagem, bom para lote misto' },
          { value: 'pixels', label: 'Em pixels', hint: 'a mesma espessura em todas' },
        ],
      },
      {
        key: 'porcento',
        type: 'range',
        label: 'Espessura',
        default: 5,
        min: 0,
        max: 50,
        step: 1,
        unit: '%',
        help: 'Do menor lado da imagem.',
        showIf: { key: 'modo', equals: 'porcento' },
      },
      {
        key: 'pixels',
        type: 'number',
        label: 'Espessura (px)',
        default: 40,
        min: 0,
        max: 2000,
        showIf: { key: 'modo', equals: 'pixels' },
      },
      { key: 'cor', type: 'text', label: 'Cor da moldura', default: '#ffffff', placeholder: '#ffffff' },
      {
        key: 'filete',
        type: 'number',
        label: 'Filete (px)',
        default: 0,
        min: 0,
        max: 40,
        help: 'A linha fina entre a foto e a moldura. Sem ela, foto clara se dissolve em moldura branca.',
      },
      {
        key: 'corDoFilete',
        type: 'text',
        label: 'Cor do filete',
        default: '#000000',
        placeholder: '#000000',
      },
      FORMATO_DE_SAIDA,
      QUALIDADE,
    ],
  },
  {
    slug: 'marca-dagua-imagem',
    operation: 'watermark-image',
    name: 'Marca d’água na imagem',
    tagline: 'Para o portfólio sair da loja marcado',
    description:
      'Escreve por cima da foto, em lote. A opção ladrilhada e inclinada é a que não se recorta fora — a marca num canto só sai com uma tesourada. Um contorno escuro acompanha o texto, senão a marca branca some justamente na foto clara, que é a que alguém copiaria.',
    icon: 'Copyright',
    accent: '71 85 105',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    cta: 'Marcar',
    fields: [
      { key: 'texto', type: 'text', label: 'Texto', default: '', placeholder: 'GreenCodes' },
      {
        key: 'posicao',
        type: 'select',
        label: 'Onde',
        default: 'diagonal',
        options: [
          { value: 'diagonal', label: 'Na diagonal, no centro' },
          { value: 'repetida', label: 'Ladrilhada', hint: 'a que não sai com um recorte' },
          { value: 'base-direita', label: 'Canto de baixo, à direita' },
          { value: 'topo-esquerda', label: 'Canto de cima, à esquerda' },
        ],
      },
      { key: 'opacidade', type: 'range', label: 'Opacidade', default: 35, min: 5, max: 100, step: 5, unit: '%' },
      {
        key: 'tamanho',
        type: 'range',
        label: 'Tamanho da letra',
        default: 8,
        min: 2,
        max: 40,
        step: 1,
        unit: '%',
        help: 'Do menor lado da imagem, para a marca ocupar a mesma fatia em retrato e em paisagem.',
      },
      { key: 'cor', type: 'text', label: 'Cor', default: '#ffffff', placeholder: '#ffffff' },
      FORMATO_DE_SAIDA,
      QUALIDADE,
    ],
  },
  {
    slug: 'juntar-imagens',
    operation: 'join-images',
    name: 'Juntar imagens',
    tagline: 'Numa tira, numa coluna ou numa grade',
    description:
      'Vira várias fotos em uma só: a tira de comprovantes, o antes e depois lado a lado, a grade do catálogo. Cada vaga fica do tamanho da maior imagem e as menores ficam centradas — esticar para igualar deformaria umas e não outras, e numa colagem isso salta aos olhos.',
    icon: 'LayoutGrid',
    accent: '132 204 22',
    category: 'Imagem',
    accept: ENTRADA,
    acceptLabel: 'imagens',
    multiple: true,
    orderable: true,
    cta: 'Juntar',
    fields: [
      {
        key: 'modo',
        type: 'select',
        label: 'Como montar',
        default: 'vertical',
        options: [
          { value: 'vertical', label: 'Uma embaixo da outra' },
          { value: 'horizontal', label: 'Lado a lado' },
          { value: 'grade', label: 'Em grade' },
        ],
      },
      {
        key: 'colunas',
        type: 'number',
        label: 'Colunas',
        default: 2,
        min: 1,
        max: 20,
        showIf: { key: 'modo', equals: 'grade' },
      },
      { key: 'espaco', type: 'number', label: 'Espaço entre elas (px)', default: 0, min: 0, max: 500 },
      { key: 'fundo', type: 'text', label: 'Cor do fundo', default: '#ffffff', placeholder: '#ffffff' },
      FORMATO_DE_SAIDA,
      QUALIDADE,
    ],
  },
];
