import { type Tool, PDF_ACCEPT, IMAGE_ACCEPT } from './tipos';

/** Ferramentas da categoria "Organizar". */
export const ORGANIZAR: Tool[] = [
  {
    slug: 'juntar-pdf',
    operation: 'merge',
    name: 'Juntar PDF',
    tagline: 'PDFs e fotos num documento só',
    description:
      'Combine quantos PDFs e imagens quiser, na ordem que você definir arrastando os cards ou ordenando de A a Z. Arquivo protegido por senha também entra: a gente pede a senha e entrega o resultado sem ela.',
    icon: 'Combine',
    accent: '20 184 166',
    category: 'Organizar',
    accept: [...PDF_ACCEPT, ...IMAGE_ACCEPT],
    acceptLabel: 'PDF ou imagem',
    multiple: true,
    orderable: true,
    cta: 'Juntar arquivos',
    fields: [
      {
        key: 'filename',
        type: 'text',
        label: 'Nome do arquivo final',
        default: 'documento-unido',
        placeholder: 'documento-unido',
      },
      {
        key: 'formatoImagem',
        type: 'select',
        label: 'Páginas vindas de imagem',
        default: 'a4',
        options: [
          { value: 'a4', label: 'A4', hint: 'a orientação segue a foto' },
          { value: 'imagem', label: 'Tamanho da própria imagem' },
        ],
        help: 'Só afeta as fotos. Os PDFs entram com o tamanho de página original.',
      },
      {
        key: 'fundoBranco',
        type: 'toggle',
        label: 'Forçar fundo branco',
        default: true,
        help: 'Alguns PDFs não desenham fundo e contam com o papel branco do leitor. Ao juntar, esse fundo some e a página sai cinza ou preta. Isto pinta branco por baixo, sem mexer no conteúdo.',
      },
    ],
  },
  {
    slug: 'organizar-paginas',
    operation: 'apply-plan',
    name: 'Organizar páginas',
    tagline: 'Reordene, gire e exclua vendo tudo',
    description:
      'Todas as páginas em miniatura: arraste para reordenar, gire uma a uma e remova o que não serve. Tudo numa passada só.',
    icon: 'LayoutGrid',
    accent: '52 211 153',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    board: 'organize',
    cta: 'Salvar documento',
    fields: [],
  },
  {
    slug: 'remover-paginas',
    operation: 'apply-plan',
    name: 'Remover páginas',
    tagline: 'Clique nas páginas que devem sair',
    description:
      'Mostramos o documento inteiro em miniaturas. Clique nas páginas que você quer fora e elas ficam marcadas, dá para conferir tudo antes de salvar.',
    icon: 'FileMinus',
    accent: '74 222 128',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    board: 'remove',
    cta: 'Remover as marcadas',
    fields: [],
  },
  {
    slug: 'extrair-paginas',
    operation: 'apply-plan',
    name: 'Extrair páginas',
    tagline: 'Clique nas páginas que quer guardar',
    description:
      'O contrário de remover: clique para selecionar as páginas que vão para o novo arquivo, na ordem original.',
    icon: 'FilePlus',
    accent: '45 212 191',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    board: 'keep',
    cta: 'Extrair as selecionadas',
    fields: [],
  },
  {
    slug: 'dividir-pdf',
    operation: 'split',
    name: 'Dividir PDF',
    tagline: 'Quebre em partes por tamanho, intervalos ou páginas',
    description:
      'Fatie por tamanho (ex: até 10MB), por intervalos de páginas ou a cada N páginas, ou extraia apenas as selecionadas. Quando gera mais de um arquivo, entregamos em .zip.',
    icon: 'Scissors',
    accent: '132 204 22',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Dividir',
    fields: [
      {
        key: 'mode',
        type: 'select',
        label: 'Como dividir',
        default: 'every',
        options: [
          { value: 'every', label: 'A cada N páginas' },
          { value: 'ranges', label: 'Por intervalos' },
          { value: 'size', label: 'Por tamanho de arquivo (MB)' },
          { value: 'extract', label: 'Extrair páginas selecionadas' },
        ],
      },
      {
        key: 'every',
        type: 'number',
        label: 'Páginas por arquivo',
        default: 1,
        min: 1,
        max: 500,
        showIf: { key: 'mode', equals: 'every' },
      },
      {
        key: 'ranges',
        type: 'text',
        label: 'Intervalos',
        default: '1-3, 4-6',
        placeholder: '1-3, 4-6, 7-',
        help: 'Cada intervalo vira um arquivo. Separe com vírgula.',
        showIf: { key: 'mode', equals: 'ranges' },
      },
      {
        key: 'maxSize',
        type: 'number',
        label: 'Tamanho máximo por arquivo (MB)',
        default: 10,
        min: 1,
        max: 500,
        step: 1,
        help: 'Dividirá o PDF em arquivos com até este tamanho limite (ex: 10 MB).',
        showIf: { key: 'mode', equals: 'size' },
      },
      {
        key: 'extractRanges',
        type: 'text',
        label: 'Páginas a extrair (manter)',
        default: '1',
        placeholder: '1, 3, 5-8',
        help: 'Gera um único PDF mantendo apenas as páginas informadas (ex: 1, 3-5).',
        showIf: { key: 'mode', equals: 'extract' },
      },
    ],
  },
  {
    slug: 'varias-por-folha',
    operation: 'n-up',
    name: 'Várias por folha',
    tagline: 'De 2 a 16 páginas por folha',
    description:
      'Monta um PDF econômico para impressão, encaixando de 2 a 16 páginas em cada folha A4. Em 2 por folha a folha deita; nas outras ela fica em pé, com a grade mais quadrada possível.',
    icon: 'Grid2x2',
    accent: '163 230 53',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Montar folhas',
    fields: [
      {
        key: 'perSheet',
        type: 'select',
        label: 'Páginas por folha',
        default: '2',
        options: [
          { value: '2', label: '2 por folha', hint: 'folha deitada, 1 x 2' },
          { value: '4', label: '4 por folha', hint: 'grade 2 x 2' },
          { value: '6', label: '6 por folha', hint: 'grade 2 x 3' },
          { value: '8', label: '8 por folha', hint: 'grade 2 x 4' },
          { value: '9', label: '9 por folha', hint: 'grade 3 x 3' },
          { value: '12', label: '12 por folha', hint: 'grade 3 x 4' },
          { value: '16', label: '16 por folha', hint: 'grade 4 x 4' },
        ],
      },
      {
        key: 'espacamentoMm',
        type: 'range',
        label: 'Espaço entre as páginas',
        default: 0,
        min: 0,
        max: 20,
        step: 1,
        unit: 'mm',
        help: 'Vão entre uma página e outra, sem tocar na beirada da folha.',
      },
      {
        key: 'margemMm',
        type: 'range',
        label: 'Margem na beirada',
        default: 0,
        min: 0,
        max: 20,
        step: 1,
        unit: 'mm',
        help: 'Zero usa a folha inteira. O PDF não precisa de margem de segurança: quem cuida disso é a impressora, na opção de ajustar a área impressa.',
      },
      { key: 'border', type: 'toggle', label: 'Desenhar moldura', default: false },
    ],
  },
  {
    slug: 'inverter-paginas',
    operation: 'reverse',
    name: 'Inverter páginas',
    tagline: 'A última vira a primeira',
    description:
      'Põe o documento de trás para frente. Resolve a digitalização feita na ordem contrária sem precisar arrastar página por página.',
    icon: 'ArrowUpDown',
    accent: '20 184 166',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Inverter ordem',
    fields: [],
  },
  {
    slug: 'intercalar-pdf',
    operation: 'interleave',
    name: 'Intercalar PDF',
    tagline: 'Frentes e versos num documento só',
    description:
      'Junta dois arquivos alternando as páginas: a 1 do primeiro, a 1 do segundo, a 2 do primeiro, e assim por diante. É o caso do escâner sem duplex, que gera as frentes num arquivo e os versos noutro.',
    icon: 'Shuffle',
    accent: '134 239 172',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: true,
    orderable: true,
    cta: 'Intercalar',
    fields: [
      {
        key: 'reverseSecond',
        type: 'toggle',
        label: 'O segundo arquivo está de trás para frente',
        default: true,
        help: 'Ao virar a pilha de papel e digitalizar de novo, os versos saem na ordem contrária. Mantenha ligado se foi assim.',
      },
    ],
  },
  {
    slug: 'dividir-paginas',
    operation: 'split-pages',
    name: 'Dividir páginas ao meio',
    tagline: 'Uma folha vira duas ou quatro',
    description:
      'Corta cada página em partes e cada parte vira uma página própria. O caso comum é livro digitalizado, em que o escâner pegou as duas páginas abertas numa imagem só.',
    icon: 'SplitSquareHorizontal',
    accent: '52 211 153',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Dividir páginas',
    fields: [
      {
        key: 'mode',
        type: 'select',
        label: 'Onde cortar',
        default: 'vertical',
        options: [
          { value: 'vertical', label: 'Ao meio, na vertical', hint: 'esquerda e direita' },
          { value: 'horizontal', label: 'Ao meio, na horizontal', hint: 'cima e baixo' },
          { value: 'quatro', label: 'Em quatro', hint: 'grade 2 x 2' },
        ],
      },
    ],
  },
  {
    slug: 'livreto-pdf',
    operation: 'booklet',
    name: 'Livreto',
    tagline: 'Ordem certa para dobrar e grampear',
    description:
      'Reorganiza as páginas para brochura: imprima frente e verso virando na borda curta, dobre a pilha ao meio e grampeie no vinco. As páginas caem na ordem de leitura.',
    icon: 'BookOpen',
    accent: '163 230 53',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Montar livreto',
    fields: [],
  },
  {
    slug: 'separar-pares-impares',
    operation: 'odd-even',
    name: 'Separar pares e ímpares',
    tagline: 'Dois arquivos: ímpares e pares',
    description:
      'Quebra o documento em dois, um com as páginas ímpares e outro com as pares. Serve para imprimir frente e verso numa impressora sem duplex.',
    icon: 'Columns2',
    accent: '20 184 166',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Separar',
    fields: [],
  },
  {
    slug: 'paginas-em-branco',
    operation: 'blank-pages',
    name: 'Inserir páginas em branco',
    tagline: 'Folhas vazias entre as páginas',
    description:
      'Acrescenta folhas em branco do mesmo tamanho das páginas do documento, no começo, no fim ou entre uma página e outra.',
    icon: 'FilePlus',
    accent: '134 239 172',
    category: 'Organizar',
    accept: PDF_ACCEPT,
    acceptLabel: 'PDF',
    multiple: false,
    cta: 'Inserir páginas',
    fields: [
      {
        key: 'where',
        type: 'select',
        label: 'Onde inserir',
        default: 'depois-de-cada',
        options: [
          { value: 'depois-de-cada', label: 'Entre uma página e outra' },
          { value: 'no-inicio', label: 'No começo do documento' },
          { value: 'no-fim', label: 'No fim do documento' },
        ],
      },
      { key: 'count', type: 'number', label: 'Quantas de cada vez', default: 1, min: 1, max: 10 },
    ],
  },
];
